-- MySQL Script generated by MySQL Workbench
-- Mon Apr 30 23:51:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apivirtu_saludencasadb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `apivirtu_saludencasadb` ;

-- -----------------------------------------------------
-- Schema apivirtu_saludencasadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apivirtu_saludencasadb` DEFAULT CHARACTER SET utf8 ;
USE `apivirtu_saludencasadb` ;

-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`categorias` (
  `pkcategoria` INT NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`pkcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`productos` (
  `pkproducto` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `caracteristicas` VARCHAR(200) NOT NULL,
  `volumen` VARCHAR(20) NOT NULL,
  `appmovil` TINYINT NOT NULL DEFAULT 0,
  `precio` DECIMAL(10,2) NOT NULL,
  `fkcategoria` INT NOT NULL,
  PRIMARY KEY (`pkproducto`),
  INDEX `fk_productos_categorias_idx` (`fkcategoria` ASC),
  CONSTRAINT `fk_productos_categorias`
    FOREIGN KEY (`fkcategoria`)
    REFERENCES `apivirtu_saludencasadb`.`categorias` (`pkcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`fotos` (
  `pkfoto` INT NOT NULL AUTO_INCREMENT,
  `ubicacion` VARCHAR(120) NOT NULL,
  `fkproducto` INT NOT NULL,
  PRIMARY KEY (`pkfoto`),
  INDEX `fk_fotos_productos1_idx` (`fkproducto` ASC),
  CONSTRAINT `fk_fotos_productos1`
    FOREIGN KEY (`fkproducto`)
    REFERENCES `apivirtu_saludencasadb`.`productos` (`pkproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`roles` (
  `pkrol` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pkrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`usuarios` (
  `pkusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nombres` VARCHAR(70) NULL,
  `apellidos` VARCHAR(70) NULL,
  `genero` TINYINT NULL COMMENT '1 = MASCULINO\n0 = FEMENINO',
  `fechanacimiento` DATE NULL COMMENT '\n',
  `primeravez` BIT NOT NULL DEFAULT 1 COMMENT '1 = TRUE\n0 = FALSE',
  `fkrol` INT NOT NULL,
  PRIMARY KEY (`pkusuario`),
  INDEX `fk_usuarios_roles1_idx` (`fkrol` ASC),
  CONSTRAINT `fk_usuarios_roles1`
    FOREIGN KEY (`fkrol`)
    REFERENCES `apivirtu_saludencasadb`.`roles` (`pkrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`compras` (
  `pkcompra` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `fkusuario` INT NOT NULL,
  `descuento` DECIMAL(10,2) NULL DEFAULT 0,
  PRIMARY KEY (`pkcompra`),
  INDEX `fk_compras_usuarios1_idx` (`fkusuario` ASC),
  CONSTRAINT `fk_compras_usuarios1`
    FOREIGN KEY (`fkusuario`)
    REFERENCES `apivirtu_saludencasadb`.`usuarios` (`pkusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`detalle_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`detalle_compra` (
  `pk_detalle_compra` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `valor_unidad` DECIMAL(10,2) NOT NULL,
  `fkcompra` INT NOT NULL,
  `fkproducto` INT NOT NULL,
  INDEX `fk_detalle_compra_compras1_idx` (`fkcompra` ASC),
  INDEX `fk_detalle_compra_productos1_idx` (`fkproducto` ASC),
  PRIMARY KEY (`pk_detalle_compra`),
  CONSTRAINT `fk_detalle_compra_compras1`
    FOREIGN KEY (`fkcompra`)
    REFERENCES `apivirtu_saludencasadb`.`compras` (`pkcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_compra_productos1`
    FOREIGN KEY (`fkproducto`)
    REFERENCES `apivirtu_saludencasadb`.`productos` (`pkproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`pagos` (
  `pkpago` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `fkcompra` INT NOT NULL,
  PRIMARY KEY (`pkpago`),
  INDEX `fk_pagos_compras1_idx` (`fkcompra` ASC),
  CONSTRAINT `fk_pagos_compras1`
    FOREIGN KEY (`fkcompra`)
    REFERENCES `apivirtu_saludencasadb`.`compras` (`pkcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`acciones_historia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`acciones_historia` (
  `pkacciones` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pkacciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`historia_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`historia_productos` (
  `pkhistoria` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora` DATETIME NOT NULL,
  `fkusuario` INT NOT NULL,
  `fkaccion` INT NOT NULL,
  `fkproducto` INT NOT NULL,
  `producto` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `caracteristicas` VARCHAR(200) NOT NULL,
  `volumen` VARCHAR(20) NOT NULL,
  `appmovil` BIT NOT NULL COMMENT '1 = TRUE\n0 = FALSE',
  `precio` DECIMAL(10,2) NOT NULL,
  `fkcategoria` INT NOT NULL,
  PRIMARY KEY (`pkhistoria`),
  INDEX `fk_historia_productos_usuarios1_idx` (`fkusuario` ASC),
  INDEX `fk_historia_productos_acciones_historia1_idx` (`fkaccion` ASC),
  INDEX `fk_historia_productos_productos1_idx` (`fkproducto` ASC),
  CONSTRAINT `fk_historia_productos_usuarios1`
    FOREIGN KEY (`fkusuario`)
    REFERENCES `apivirtu_saludencasadb`.`usuarios` (`pkusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historia_productos_acciones_historia1`
    FOREIGN KEY (`fkaccion`)
    REFERENCES `apivirtu_saludencasadb`.`acciones_historia` (`pkacciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historia_productos_productos1`
    FOREIGN KEY (`fkproducto`)
    REFERENCES `apivirtu_saludencasadb`.`productos` (`pkproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apivirtu_saludencasadb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apivirtu_saludencasadb`.`carrito` (
  `pkcarrito` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `fkusuario` INT NOT NULL,
  `fkproducto` INT NOT NULL,
  PRIMARY KEY (`pkcarrito`),
  INDEX `fk_carrito_usuarios1_idx` (`fkusuario` ASC),
  INDEX `fk_carrito_productos1_idx` (`fkproducto` ASC),
  CONSTRAINT `fk_carrito_usuarios1`
    FOREIGN KEY (`fkusuario`)
    REFERENCES `apivirtu_saludencasadb`.`usuarios` (`pkusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrito_productos1`
    FOREIGN KEY (`fkproducto`)
    REFERENCES `apivirtu_saludencasadb`.`productos` (`pkproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
